import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [name, setName] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const agifyResponse = await fetch(`https://api.agify.io?name=${name}`);
      const agifyData = await agifyResponse.json();

      const genderizeResponse = await fetch(
        `https://api.genderize.io?name=${name}`
      );
      const genderizeData = await genderizeResponse.json();

      const nationalizeResponse = await fetch(
        `https://api.nationalize.io?name=${name}`
      );
      const nationalizeData = await nationalizeResponse.json();

      setResult({
        age: agifyData.age,
        gender: genderizeData.gender,
        countries: nationalizeData.country.map((c) => c.country_id),
      });
    } catch (err) {
      setError("Failed to fetch data. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleNameChange = (e) => {
    const name = e.target.value;
    setName(name);
    if (name == "") {
      setResult(null);
    }
  };

  return (
    <>
      <Head>
        <title>Age Gusser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            fontFamily: "Arial, sans-serif",
            padding: "20px",
            maxWidth: "600px",
            margin: "0 auto",
          }}
        >
          <h1>Guess Age, Gender, and Nationality</h1>
          <form onSubmit={handleSubmit} style={{ marginBottom: "20px" }}>
            <input
              type="text"
              value={name}
              onChange={handleNameChange}
              placeholder="Enter a name"
              required
              style={{ padding: "10px", fontSize: "16px", marginRight: "10px" }}
            />
            <button
              type="submit"
              style={{ padding: "10px 20px", fontSize: "16px" }}
            >
              {loading ? "Guessing" : "Guess"}
            </button>
          </form>

          {loading && <p>Loading...</p>}

          {error && <p style={{ color: "red" }}>{error}</p>}

          {result && (
            <div>
              <h2>Results for {name}</h2>
              <p>
                <strong>Age:</strong> {result.age}
              </p>
              <p>
                <strong>Gender:</strong> {result.gender}
              </p>
              <p>
                <strong>Countries:</strong> {result.countries.join(", ")}
              </p>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
